"""
E2E Test Suite Configuration & Chapter Specifications Catalog
"""
from pathlib import Path
from typing import Dict, List, Any

# Root project paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MAIN_TEX = PROJECT_ROOT / "main.tex"
MAIN_PDF = PROJECT_ROOT / "appuntiEconomia.pdf" if (PROJECT_ROOT / "appuntiEconomia.pdf").exists() else PROJECT_ROOT / "main.pdf"
MAIN_LOG = PROJECT_ROOT / "main.log"
MAIN_TOC = PROJECT_ROOT / "main.toc"
CONFIG_DIR = PROJECT_ROOT / "config"
CHAPTERS_DIR = PROJECT_ROOT / "chapters"
FIGURES_DIR = PROJECT_ROOT / "figures"
TESTS_DIR = PROJECT_ROOT / "tests"

# Packages, environments, macros configuration files
PACKAGES_TEX = CONFIG_DIR / "packages.tex"
ENVIRONMENTS_TEX = CONFIG_DIR / "environments.tex"
MACROS_TEX = CONFIG_DIR / "macros.tex"

# All recognized tcolorbox environments from config/environments.tex
RECOGNIZED_TCOLORBOX_ENVS = [
    "definizione",
    "modello",
    "legge",
    "teorema",
    "dimostrazione",
    "metodo",
    "esame",
    "esempio",
    "esercizio",
    "osservazione",
    "empirico",
]

# Standard macros defined in config/macros.tex
STANDARD_MACROS = {
    "differential": [r"\dd", r"\dv", r"\dvtwo", r"\pdv", r"\pdvtwo"],
    "logic": [r"\implica", r"\sse", r"\eps"],
    "micro": [
        r"\Qd", r"\Qs", r"\Qeq", r"\Peq", r"\epsp", r"\epsr", r"\epsxy",
        r"\SMS", r"\SMST", r"\U", r"\RT", r"\RMg", r"\RME", r"\CT",
        r"\CF", r"\CV", r"\CMg", r"\CME", r"\CMEF", r"\CMEV",
        r"\profit", r"\surplusC", r"\surplusP", r"\surplusT", r"\lossDW"
    ],
    "macro": [
        r"\PIL", r"\PNL", r"\SA", r"\DA", r"\OA", r"\PMgC", r"\PMgS",
        r"\PMgM", r"\IS", r"\LM", r"\BP", r"\MD", r"\MS", r"\BM",
        r"\infl", r"\inflexp", r"\unemp", r"\unempnat", r"\cambionom", r"\cambioreal"
    ],
}

# Chapter Requirements Catalog
CHAPTER_SPECS: Dict[str, Dict[str, Any]] = {
    "01_scienza_economica": {
        "num": 1,
        "title": "Scienza Economica ed Economia",
        "label": "chap:scienza_economica",
        "milestone": "M0",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "legge", "metodo", "esame", "esempio", "osservazione"],
        "expected_macros": [r"\RT", r"\CT", r"\CMg"],
        "key_formula_patterns": [
            r"\\mathrm\{BMg\}",
            r"\\mathrm\{CMg\}",
            r"\\text\{Costo Opportunit",
            r"\\Pi",
        ],
        "expected_figures": ["fig:apprendimento_economia"],
        "part": "I",
    },
    "02_strumenti_analisi_economica": {
        "num": 2,
        "title": "Gli Strumenti dell'Analisi Economica",
        "label": "chap:strumenti_analisi_economica",
        "milestone": "M1",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "osservazione"],
        "expected_macros": [r"\dv", r"\eps"],
        "key_formula_patterns": [
            r"\\text\{Valore Reale\}",
            r"I_t",
            r"\\Delta\\%",
            r"\\dv",
        ],
        "expected_figures": [],
        "part": "I",
    },
    "03_domanda_offerta_mercato": {
        "num": 3,
        "title": "Domanda, Offerta e Mercato",
        "label": "chap:domanda_offerta_mercato",
        "milestone": "M2",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "legge", "metodo", "esame"],
        "expected_macros": [r"\Qd", r"\Qs", r"\Qeq", r"\Peq", r"\surplusC", r"\surplusP", r"\lossDW"],
        "key_formula_patterns": [
            r"Q_d",
            r"Q_s",
            r"P\^\\*",
            r"\\surplusC|SC|Surplus",
        ],
        "expected_figures": ["fig:equilibrio_mercato"],
        "part": "II",
    },
    "04_elasticita_domanda_offerta": {
        "num": 4,
        "title": "Elasticità della Domanda e dell'Offerta",
        "label": "chap:elasticita_domanda_offerta",
        "milestone": "M2",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "legge", "metodo", "esame"],
        "expected_macros": [r"\epsp", r"\epsr", r"\epsxy", r"\RMg", r"\RT", r"\dv"],
        "key_formula_patterns": [
            r"\\epsp|\\varepsilon_p|\\varepsilon_\\{\\mathrm\{p\}\\}",
            r"\\RMg|RMg",
            r"\\RT|RT",
        ],
        "expected_figures": [],
        "part": "II",
    },
    "05_scelta_consumatore_domanda": {
        "num": 5,
        "title": "Teoria della Scelta del Consumatore e della Domanda",
        "label": "chap:scelta_consumatore_domanda",
        "milestone": "M2",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "legge", "metodo", "esame"],
        "expected_macros": [r"\SMS", r"\U", r"\pdv"],
        "key_formula_patterns": [
            r"\\SMS|SMS",
            r"p_1.*x_1.*p_2.*x_2.*R",
            r"U_1.*U_2|\\pdv\{U\}",
        ],
        "expected_figures": [],
        "part": "II",
    },
    "06_introduzione_teoria_offerta": {
        "num": 6,
        "title": "Introduzione alla Teoria dell'Offerta",
        "label": "chap:introduzione_teoria_offerta",
        "milestone": "M3",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\RT", r"\CT", r"\RMg", r"\CMg", r"\profit", r"\dv"],
        "key_formula_patterns": [
            r"\\profit|\\Pi",
            r"\\RMg.*=.*\\CMg|RMg.*=.*CMg",
            r"\\dv\{\\Pi\}|\\dv\{\\RT\}",
        ],
        "expected_figures": [],
        "part": "II",
    },
    "07_tecnologia_costi": {
        "num": 7,
        "title": "La Teoria dell'Offerta: Tecnologia e Costi",
        "label": "chap:tecnologia_costi",
        "milestone": "M3",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "legge", "metodo", "esame"],
        "expected_macros": [r"\SMST", r"\CT", r"\CF", r"\CV", r"\CMg", r"\CME", r"\CMEF", r"\CMEV"],
        "key_formula_patterns": [
            r"\\SMST|SMST",
            r"\\CMg|CMg",
            r"\\CME|CMe",
            r"\\CF.*\\CV|CF.*CV",
        ],
        "expected_figures": [],
        "part": "II",
    },
    "08_strutture_mercato": {
        "num": 8,
        "title": "Strutture di Mercato: Concorrenza, Monopolio e Oligopolio",
        "label": "chap:strutture_mercato",
        "milestone": "M3",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\RMg", r"\CMg", r"\lossDW", r"\epsp", r"\profit"],
        "key_formula_patterns": [
            r"Lerner|L\s*=",
            r"Cournot|Stackelberg|Bertrand",
            r"P.*=.*\\CMg|P.*>.*\\CMg",
        ],
        "expected_figures": [],
        "part": "III",
    },
    "09_informazione_rischio": {
        "num": 9,
        "title": "Informazione, Rischio e Asimmetrie Informative",
        "label": "chap:informazione_rischio",
        "milestone": "M3",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\U"],
        "key_formula_patterns": [
            r"EV|Valore\s+Atteso",
            r"EU|Utilit[aà]\s+Attesa",
            r"CE|Equivalente\s+Certo",
            r"RP|Premio.*Rischio",
        ],
        "expected_figures": [],
        "part": "III",
    },
    "10_introduzione_macroeconomia": {
        "num": 10,
        "title": "Introduzione alla Macroeconomia",
        "label": "chap:introduzione_macroeconomia",
        "milestone": "M4",
        "min_lines_draft": 35,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\PIL", r"\PNL"],
        "key_formula_patterns": [
            r"\\PIL|PIL",
            r"C\s*\+\s*I\s*\+\s*G",
            r"Deflatore|IPC",
        ],
        "expected_figures": [],
        "part": "IV",
    },
    "11_prodotto_nazionale_spesa_aggregata": {
        "num": 11,
        "title": "Prodotto Nazionale e Spesa Aggregata",
        "label": "chap:prodotto_nazionale_spesa_aggregata",
        "milestone": "M4",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\SA", r"\PMgC", r"\PMgS"],
        "key_formula_patterns": [
            r"\\SA|SA|Spesa\s+Aggregata",
            r"\\PMgC|PMgC|c_1|c\s*\*",
            r"\\frac\{1\}\{1\s*-\s*c\}|moltiplicatore",
        ],
        "expected_figures": [],
        "part": "IV",
    },
    "12_politica_fiscale_commercio_estero": {
        "num": 12,
        "title": "Politica Fiscale e Commercio Estero",
        "label": "chap:politica_fiscale_commercio_estero",
        "milestone": "M4",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\PMgM", r"\SA"],
        "key_formula_patterns": [
            r"BS|Bilancio|Disavanzo",
            r"NX|Esportazioni\s+Nette",
            r"1\s*-\s*c\(1-t\)",
        ],
        "expected_figures": [],
        "part": "IV",
    },
    "13_moneta_politica_monetaria": {
        "num": 13,
        "title": "La Moneta e la Politica Monetaria",
        "label": "chap:moneta_politica_monetaria",
        "milestone": "M4",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\MD", r"\MS", r"\BM"],
        "key_formula_patterns": [
            r"\\BM|BM|Base\s+Monetaria",
            r"\\MD|\\MS|M\^d|M\^s",
            r"moltiplicatore.*monet",
        ],
        "expected_figures": [],
        "part": "IV",
    },
    "14_mercato_monetario_reale_is_lm": {
        "num": 14,
        "title": "Mercato Monetario e Mercato Reale: Il Modello IS-LM",
        "label": "chap:mercato_monetario_reale_is_lm",
        "milestone": "M5",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\IS", r"\LM", r"\SA", r"\MD", r"\MS"],
        "key_formula_patterns": [
            r"\\IS|IS",
            r"\\LM|LM",
            r"crowding.*out|spiazzamento",
        ],
        "expected_figures": [],
        "part": "V",
    },
    "15_equilibrio_domanda_offerta_aggregata": {
        "num": 15,
        "title": "Equilibrio Domanda-Offerta Aggregata: Il Modello AD-AS",
        "label": "chap:equilibrio_domanda_offerta_aggregata",
        "milestone": "M5",
        "min_lines_draft": 35,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\DA", r"\OA", r"\IS", r"\LM"],
        "key_formula_patterns": [
            r"\\DA|\\AD|AD",
            r"\\OA|\\AS|AS|SRAS|LRAS",
            r"stagflazione|piena\s+occupazione",
        ],
        "expected_figures": [],
        "part": "V",
    },
    "16_inflazione_disoccupazione": {
        "num": 16,
        "title": "Inflazione e Disoccupazione",
        "label": "chap:inflazione_disoccupazione",
        "milestone": "M5",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\infl", r"\inflexp", r"\unemp", r"\unempnat"],
        "key_formula_patterns": [
            r"Phillips",
            r"NAIRU|tasso\s+naturale",
            r"\\infl|\\pi",
            r"Okun",
        ],
        "expected_figures": [],
        "part": "V",
    },
    "17_tassi_cambio_bilancia_pagamenti": {
        "num": 17,
        "title": "I Tassi di Cambio e la Bilancia dei Pagamenti",
        "label": "chap:tassi_cambio_bilancia_pagamenti",
        "milestone": "M5",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\cambionom", r"\cambioreal", r"\BP"],
        "key_formula_patterns": [
            r"\\cambioreal|\\varepsilon_r|cambio\s+reale",
            r"PPP|Parit[aà].*Potere",
            r"UIP|Parit[aà].*Tassi",
            r"Marshall-Lerner|Curva\s+a\s+J",
        ],
        "expected_figures": [],
        "part": "V",
    },
    "18_macroeconomia_sistemi_aperti": {
        "num": 18,
        "title": "Macroeconomia dei Sistemi Economici Aperti",
        "label": "chap:macroeconomia_sistemi_aperti",
        "milestone": "M5",
        "min_lines_draft": 40,
        "min_lines_mature": 250,
        "min_words_mature": 2000,
        "required_envs": ["definizione", "modello", "metodo", "esame"],
        "expected_macros": [r"\IS", r"\LM", r"\BP", r"\cambionom"],
        "key_formula_patterns": [
            r"\\BP|BP",
            r"Mundell-Fleming",
            r"Trilemma|Trinit[aà]\s+Impossibile",
            r"cambi\s+fissi|cambi\s+flessibili",
        ],
        "expected_figures": [],
        "part": "V",
    },
}
